#!/bin/sh
#
# distclean Miroslav Zagorac <mzagorac@haproxy.com>
#
test -f Makefile && make maintainer-clean

rm -rf autom4te.cache config package _*
rm -f autoscan.log configure.scan aclocal.m4 config.log config.status configure
rm -f Makefile.in */Makefile.in m4/l* src/.source-md5sums
